spring.application.name=coffee-break-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
# todo: delete later, only for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true