/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeOffersRouteImport } from './routes/employee.offers'
import { Route as EmployeeLocationsRouteImport } from './routes/employee.locations'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as EmployeeOffersNewRouteImport } from './routes/employee.offers.new'
import { Route as EmployeeOffersAllRouteImport } from './routes/employee.offers.all'
import { Route as EmployeeLocationsNewRouteImport } from './routes/employee.locations.new'
import { Route as EmployeeLocationsAllRouteImport } from './routes/employee.locations.all'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeOffersRoute = EmployeeOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLocationsRoute = EmployeeLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOffersNewRoute = EmployeeOffersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployeeOffersRoute,
} as any)
const EmployeeOffersAllRoute = EmployeeOffersAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => EmployeeOffersRoute,
} as any)
const EmployeeLocationsNewRoute = EmployeeLocationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployeeLocationsRoute,
} as any)
const EmployeeLocationsAllRoute = EmployeeLocationsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => EmployeeLocationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/locations': typeof EmployeeLocationsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRouteWithChildren
  '/employee/locations/all': typeof EmployeeLocationsAllRoute
  '/employee/locations/new': typeof EmployeeLocationsNewRoute
  '/employee/offers/all': typeof EmployeeOffersAllRoute
  '/employee/offers/new': typeof EmployeeOffersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/locations': typeof EmployeeLocationsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRouteWithChildren
  '/employee/locations/all': typeof EmployeeLocationsAllRoute
  '/employee/locations/new': typeof EmployeeLocationsNewRoute
  '/employee/offers/all': typeof EmployeeOffersAllRoute
  '/employee/offers/new': typeof EmployeeOffersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/locations': typeof EmployeeLocationsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRouteWithChildren
  '/employee/locations/all': typeof EmployeeLocationsAllRoute
  '/employee/locations/new': typeof EmployeeLocationsNewRoute
  '/employee/offers/all': typeof EmployeeOffersAllRoute
  '/employee/offers/new': typeof EmployeeOffersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/locations'
    | '/login'
    | '/offers'
    | '/orders'
    | '/employee/dashboard'
    | '/employee/locations'
    | '/employee/offers'
    | '/employee/locations/all'
    | '/employee/locations/new'
    | '/employee/offers/all'
    | '/employee/offers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/locations'
    | '/login'
    | '/offers'
    | '/orders'
    | '/employee/dashboard'
    | '/employee/locations'
    | '/employee/offers'
    | '/employee/locations/all'
    | '/employee/locations/new'
    | '/employee/offers/all'
    | '/employee/offers/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/locations'
    | '/login'
    | '/offers'
    | '/orders'
    | '/employee/dashboard'
    | '/employee/locations'
    | '/employee/offers'
    | '/employee/locations/all'
    | '/employee/locations/new'
    | '/employee/offers/all'
    | '/employee/offers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/offers': {
      id: '/employee/offers'
      path: '/offers'
      fullPath: '/employee/offers'
      preLoaderRoute: typeof EmployeeOffersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/locations': {
      id: '/employee/locations'
      path: '/locations'
      fullPath: '/employee/locations'
      preLoaderRoute: typeof EmployeeLocationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/offers/new': {
      id: '/employee/offers/new'
      path: '/new'
      fullPath: '/employee/offers/new'
      preLoaderRoute: typeof EmployeeOffersNewRouteImport
      parentRoute: typeof EmployeeOffersRoute
    }
    '/employee/offers/all': {
      id: '/employee/offers/all'
      path: '/all'
      fullPath: '/employee/offers/all'
      preLoaderRoute: typeof EmployeeOffersAllRouteImport
      parentRoute: typeof EmployeeOffersRoute
    }
    '/employee/locations/new': {
      id: '/employee/locations/new'
      path: '/new'
      fullPath: '/employee/locations/new'
      preLoaderRoute: typeof EmployeeLocationsNewRouteImport
      parentRoute: typeof EmployeeLocationsRoute
    }
    '/employee/locations/all': {
      id: '/employee/locations/all'
      path: '/all'
      fullPath: '/employee/locations/all'
      preLoaderRoute: typeof EmployeeLocationsAllRouteImport
      parentRoute: typeof EmployeeLocationsRoute
    }
  }
}

interface EmployeeLocationsRouteChildren {
  EmployeeLocationsAllRoute: typeof EmployeeLocationsAllRoute
  EmployeeLocationsNewRoute: typeof EmployeeLocationsNewRoute
}

const EmployeeLocationsRouteChildren: EmployeeLocationsRouteChildren = {
  EmployeeLocationsAllRoute: EmployeeLocationsAllRoute,
  EmployeeLocationsNewRoute: EmployeeLocationsNewRoute,
}

const EmployeeLocationsRouteWithChildren =
  EmployeeLocationsRoute._addFileChildren(EmployeeLocationsRouteChildren)

interface EmployeeOffersRouteChildren {
  EmployeeOffersAllRoute: typeof EmployeeOffersAllRoute
  EmployeeOffersNewRoute: typeof EmployeeOffersNewRoute
}

const EmployeeOffersRouteChildren: EmployeeOffersRouteChildren = {
  EmployeeOffersAllRoute: EmployeeOffersAllRoute,
  EmployeeOffersNewRoute: EmployeeOffersNewRoute,
}

const EmployeeOffersRouteWithChildren = EmployeeOffersRoute._addFileChildren(
  EmployeeOffersRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeLocationsRoute: typeof EmployeeLocationsRouteWithChildren
  EmployeeOffersRoute: typeof EmployeeOffersRouteWithChildren
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeLocationsRoute: EmployeeLocationsRouteWithChildren,
  EmployeeOffersRoute: EmployeeOffersRouteWithChildren,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
